### ISSUE TITLE
Compile errors with v1.22c-102-gd23a537

### ISSUE THREAD

**Issue by iamdoubz** [yrutschle/sslh#330]
Using a fresh `git clone` I receive the following errors:

```bash
iamdoubz@computer:~/Gits/sslh2$ make
cc -Wall -DLIBPCRE -g -fprofile-arcs -ftest-coverage -fsanitize=address -fsanitize=leak -fsanitize=undefined  -o sslh-fork sslh-conf.o common.o log.o sslh-main.o probe.o tls.o argtable3.o collection.o gap.o sslh-fork.o  -lm -lpcre2-8 -lwrap -lconfig -lcap -lsystemd -lbsd
#strip sslh-fork
cc -Wall -DLIBPCRE -g -fprofile-arcs -ftest-coverage -fsanitize=address -fsanitize=leak -fsanitize=undefined  -o sslh-select sslh-conf.o common.o log.o sslh-main.o probe.o tls.o argtable3.o collection.o gap.o processes.o udp-listener.o sslh-select.o hash.o -lm -lpcre2-8 -lwrap -lconfig -lcap -lsystemd -lbsd
#strip sslh-select
cc -Wall -DLIBPCRE -g -fprofile-arcs -ftest-coverage -fsanitize=address -fsanitize=leak -fsanitize=undefined  -o sslh-ev sslh-conf.o common.o log.o sslh-main.o probe.o tls.o argtable3.o collection.o gap.o processes.o udp-listener.o sslh-ev.o hash.o -lm -lpcre2-8 -lwrap -lconfig -lcap -lsystemd -lbsd -lev
#strip sslh-ev
pod2man --section=8 --release=v1.22c-102-gd23a537-dirty --center=" " sslh.pod | gzip -9 - > sslh.8.gz
cc -Wall -DLIBPCRE -g -fprofile-arcs -ftest-coverage -fsanitize=address -fsanitize=leak -fsanitize=undefined -DLIBWRAP -DENABLE_REGEX -DLIBCONFIG -DLIBCAP -DSYSTEMD -DLIBBSD -c systemd-sslh-generator.c
In file included from systemd-sslh-generator.c:5:
systemd-sslh-generator.c: In function ‘resolve_listen’:
common.h:56:9: warning: implicit declaration of function ‘print_message’ [-Wimplicit-function-declaration]
   56 |         print_message(msg_system_error, "%s:%d:", __FILE__, __LINE__); \
      |         ^~~~~~~~~~~~~
systemd-sslh-generator.c:12:5: note: in expansion of macro ‘CHECK_ALLOC’
   12 |     CHECK_ALLOC(conn, "malloc");
      |     ^~~~~~~~~~~
common.h:56:23: error: ‘msg_system_error’ undeclared (first use in this function)
   56 |         print_message(msg_system_error, "%s:%d:", __FILE__, __LINE__); \
      |                       ^~~~~~~~~~~~~~~~
systemd-sslh-generator.c:12:5: note: in expansion of macro ‘CHECK_ALLOC’
   12 |     CHECK_ALLOC(conn, "malloc");
      |     ^~~~~~~~~~~
common.h:56:23: note: each undeclared identifier is reported only once for each function it appears in
   56 |         print_message(msg_system_error, "%s:%d:", __FILE__, __LINE__); \
      |                       ^~~~~~~~~~~~~~~~
systemd-sslh-generator.c:12:5: note: in expansion of macro ‘CHECK_ALLOC’
   12 |     CHECK_ALLOC(conn, "malloc");
      |     ^~~~~~~~~~~
systemd-sslh-generator.c: In function ‘get_listen_from_conf’:
common.h:56:23: error: ‘msg_system_error’ undeclared (first use in this function)
   56 |         print_message(msg_system_error, "%s:%d:", __FILE__, __LINE__); \
      |                       ^~~~~~~~~~~~~~~~
systemd-sslh-generator.c:46:13: note: in expansion of macro ‘CHECK_ALLOC’
   46 |             CHECK_ALLOC(*listen, "malloc");
      |             ^~~~~~~~~~~
systemd-sslh-generator.c: In function ‘gen_sslh_config’:
common.h:56:23: error: ‘msg_system_error’ undeclared (first use in this function)
   56 |         print_message(msg_system_error, "%s:%d:", __FILE__, __LINE__); \
      |                       ^~~~~~~~~~~~~~~~
systemd-sslh-generator.c:122:9: note: in expansion of macro ‘CHECK_ALLOC’
  122 |         CHECK_ALLOC(runtime_conf, "malloc");
      |         ^~~~~~~~~~~
make: *** [Makefile:76: systemd-sslh-generator.o] Error 1
```
Top of Makefile:

```makefile
ENABLE_SANITIZER=0 # Enable ASAN/LSAN/UBSAN
ENABLE_REGEX=1  # Enable regex probes
USELIBCONFIG=1  # Use libconfig? (necessary to use configuration files)
USELIBWRAP?=1   # Use libwrap?
USELIBCAP=1     # Use libcap?
USESYSTEMD=1     # Make use of systemd socket activation
USELIBBSD?=1     # Use libbsd (needed to update process name in `ps`)
COV_TEST=1      # Perform test coverage?
PREFIX?=/usr
BINDIR?=$(PREFIX)/sbin
MANDIR?=$(PREFIX)/share/man/man8
```

**Comment by licaon-kter** [comment]
OS version?

**Comment by iamdoubz** [comment]
Ubuntu 20.04

**Comment by yrutschle** [comment]
Indeed -- systemd-sslh-generator relies on macros in common.h, which now use the new logging system, which requires pulling log.o in, which depends on the sslh configuration...

I need to look into the actual dependencies here. Thanks for the report :-)

**Comment by iamdoubz** [comment]
Just reporting back that it compiled and installed just fine after I pulled [78827d7](https://github.com/yrutschle/sslh/commit/78827d75fe0b215ed32542f83ca5527f2e31f4b2). Just some new strange logging messages in `journalctl` that I will not pay any attention to.

```bash
May 05 09:04:29 computer sslh[10184]: ==10184==Can't open /proc/10181/task for reading.
May 05 09:04:29 computer sslh[10181]: ==10181==LeakSanitizer has encountered a fatal error.
May 05 09:04:29 computer sslh[10181]: ==10181==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
May 05 09:04:29 computer sslh[10181]: ==10181==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
```

Also, when I run `sslh --version`:
```bash
iamdoubz@computer:~$ sslh --version
sslh-ev v1.22c-105-g78827d7-dirty

=================================================================
==8945==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f8cb06f8a06 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x7f8cb03f2ada in config_init (/lib/x86_64-linux-gnu/libconfig.so.9+0x3ada)
    #2 0x560ea8408153 in main /home/iamdoubz/Gits/sslh2/sslh-main.c:199
    #3 0x7f8caf7cd0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)

SUMMARY: AddressSanitizer: 64 byte(s) leaked in 1 allocation(s).
```

**Comment by yrutschle** [comment]
Yes, that's harmless enough: it's the sanitizer stuff complaining.
Your Makefile unintuitively enables it, what you want is:
```
ENABLE_SANITIZER= # Enable ASAN/LSAN/UBSAN
```

(I have long wondered how to make this more intuitive, but digging through make's documentation is not very high on my motivation list...)

**Comment by iamdoubz** [comment]
Yes I assumed (incorrectly no doubt) that if I set it to 0, it wouldn't compile that part... null is best? That should be some IT companies slogan I think.
